### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by crystaldust** [crystaldust/ros2cli#1]
- [x] Add rclpy components support to get_package_component_types:
https://github.com/crystaldust/ros2cli/blob/7362d35c8f6bbf74b824f271c57e77a6b7c2c269/ros2component/ros2component/verb/types.py#L36-L39

- [ ] Determine where to put component resource type(i.e. rclpy_components or rclcpp_components) in the output of  `ros2 component types`

- [ ] Other functions that require changes(arg completer, standalone verb...)
